from exception import *

def func1():
    add()
    print("this is fucntion1")


def func2():
    print("this is fucntion2")

def main():
    func1()
    func2()


if __name__=="__main__":
    main()

    